### PR TITLE
Add WASI platform support

### PR DESCRIPTION
**Pull request by whitequark**
See https://github.com/YosysHQ/icestorm/pull/260 for motivation for the way ecpbram is changed.

### CODE REVIEW

**Comment by whitequark** [comment]
> What's annoying with that change in behavior is that "random" init files generated as part of a make file and that were previously different (to init different BRAMs) now might be the same and thus screw up the design ...

This code is very confusingly written (both in ecpbram and icebram) but that's actually not what will happen. After the change (again both in ecpbram and icebram) if you do not specify `-s` then you'll get a random hex file based on the *current time*. So if previously your code happened to work because you relied on PIDs being unique (which they are not), it will keep working because you rely on current time being unique (which it is not).

The only thing that changes is that, if you *do* use `-s`, then you will *always* get the same init contents.

**Comment by whitequark** [comment]
Also AFAIU it won't silently break the design but rather return an error about "conflicting pattern" which is easy to fix by adding `-s`.

**Comment by smunaut** [comment]
Huh ... if you use `-s` you already got the same init content. The `seed_nr` is overwritten if `-s` is specified.

I know PID and time are not unique. The time especially might not be in a makefile execute in // (but in that case chances the PID will be different), and PID might rollover but probably not within the same microsecond. So the chances of both of them not being unique at the very same time is IMHO fair to ignore which is why it's nice to include both in the seed if none is specified.

Wrt to "conflicting pattern": Mmm, no that's to detect a bad pattern file, but doesn't check anything in the design itself. `icebram` has soem code to check the number of replacement that has occured and that I apparently forgot to copy, but even then it's a just an info, not an error since it might be perfectly valid to have several copy of the same ROM / module in a design.

**Comment by whitequark** [comment]
@smunaut Agh. You're right, this code is just really badly written. Thanks for correcting me on this.

**Comment by daveshah1** [comment]
> not an error since it might be perfectly valid to have several copy of the same ROM / module in a design

particularly if a memory has been duplicated to meet a read port requirement...

**Comment by whitequark** [comment]
@smunaut Looks good now?

**Comment by smunaut** [comment]
:+1:

**Pull request merged**
