### PR TITLE
Fix building without git

### PR DESCRIPTION
**Pull request by L-as**
If git isn't present, don't try to cache the build configuration.

### CODE REVIEW

**Comment by gatecat** [comment]
Hmm, looks like this handles the case of git having existed in the past (and thus those files being generated) but not any more, but doesn't handle what I'd expect to be the more common case of git never existing?

Am I mistaken or is there a particular reason for this I'm missing?

**Comment by L-as** [comment]
You do seem to be mistaken, since it works for me in a Nix sandbox without Git.

**Comment by gatecat** [comment]
I'm curious now, if you run `ecppack` with no arguments from your build, what version does it print?

**Comment by L-as** [comment]
```
Error: input file is mandatory.

Project Trellis - Open Source Tools for ECP5 FPGAs
Version 
./result/bin/ecppack: ECP5 bitstream packer

Copyright (C) 2018 gatecat <gatecat@ds0.me>

Usage: ./result/bin/ecppack input.config [output.bit] [options]
Allowed options:
  -h [ --help ]         show help
  -v [ --verbose ]      verbose output
  --db arg              Trellis database folder location
  --usercode arg        USERCODE to set in bitstream
  --idcode arg          IDCODE to override in bitstream
  --freq arg            config frequency in MHz
  --svf arg             output SVF file
  --svf-rowsize arg     SVF row size in bits (default 8000)
  --compress            compress bitstream to reduce size
  --spimode arg         SPI Mode to use (fast-read, dual-spi, qspi)
  --background          enable background reconfiguration in bitstream
  --delta arg           create a delta partial bitstream given a reference 
                        config
  --bootaddr arg        set next BOOTADDR in bitstream and enable multi-boot
  --input arg           input textual configuration
  --bit arg             output bitstream file
  --version             show current version and exit

*** Exception: CmdException (Exited (ExitFailure 1))
```

It just doesn't have a version.

**Comment by L-as** [comment]
Thanks!

**Pull request merged**
