### PR TITLE
MachXO2/XO3/XO3D timing fuzzing

### PR DESCRIPTION
**Pull request by mmicko**
Extends https://github.com/YosysHQ/prjtrellis/pull/229 with  XO2 and XO3D support and add more designs to get fuzzing results

### CODE REVIEW

**Comment by mmicko** [comment]
Require https://github.com/YosysHQ/prjtrellis-db/pull/14 changes, so database can be updated after merge

**Review by Ravenslofty — COMMENTED** [review]
So, I'm not entirely awake yet, but I remember needing to manually edit the SDF files in order for it to detect XO3 logic timings, due to diamond considering each LUT to be an instance of itself. Is that still necessary with this, or did I overlook a fix?

**Review by Ravenslofty — APPROVED** [review]

**Comment by mmicko** [comment]
Updated database

**Comment by gatecat** [comment]
Thanks!

**Pull request merged**
