### PR TITLE
MachXO2

### PR DESCRIPTION
**Pull request by mmicko**
Fuzzers update for all models except XO2-256 and XO2-640

All is tested on XO2-7000HE and XO2-1200HC boards

### CODE REVIEW

**Comment by mmicko** [comment]
@cr1901 Any feedback on this ?

**Comment by cr1901** [comment]
@mmicko This all looks fine to me. Two of the bitstreams I used to test have a few unknown bits remaining, but from checking in EPIC, these bits _all_ involve the secondary global routing that we're not using. At this point, w/ this PR along w/ the database pull, I would be comfortable using `nextpnr-machxo2` for non-toy designs.

Ty for your effort :).

**Comment by gatecat** [comment]
How much stuff is _actually_ different from the MachXO3? Is it possible that a bunch of copy and paste could have been avoided?

**Comment by mmicko** [comment]
I/O are different that is certain. Agree that there are lot of things that fully identical, and also that some of data could be reused, but you do not see differences until you have all the things fuzzed. I have optimized scripts a lot by comparing end results after hours of fuzzing data that end up identical to some other cell. Usually it ends up having same interconnect but different global routing, or some additional enums.

**Comment by gatecat** [comment]
Okay, sounds good to me then

**Comment by mmicko** [comment]
@gatecat please do merge https://github.com/YosysHQ/prjtrellis-db/pull/13 and I will update database link

**Pull request merged**
